# @package _global_
defaults:
  - /habitat: habitat_config_base
  - /habitat/task: pointnav
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbd_agent
  - /habitat/dataset/pointnav: habitat_test
  - _self_
habitat:
  environment:
    max_episode_steps: 20
  task:
    measurements:
      distance_to_goal:
        type: DistanceToGoal
        distance_to: POINT
      success:
        type: Success
        success_distance: 0.2
      spl:
        type: SPL
      distance_to_goal_reward:
        type: DistanceToGoalReward
  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 256
            height: 256
          depth_sensor:
            width: 256
            height: 256

  dataset:
    split: "train"
    data_path: "/data/xwy/storage/habitat-dataset/pointnav_gibson_v1/train/train.json.gz"
    scenes_dir: "/data/xwy/storage/habitat-dataset/gibson_habitat"

